FROM debian:wheezy

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN groupadd -r mysql && useradd -r -g mysql mysql

# FATAL ERROR: please install the following Perl modules before executing /usr/local/mysql/scripts/mysql_install_db:
# File::Basename
# File::Copy
# Sys::Hostname
# Data::Dumper
RUN apt-get update && apt-get install -y perl --no-install-recommends && rm -rf /var/lib/apt/lists/*

# install tools
RUN apt-get update && apt-get install -y wget --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y libaio1 --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y apt-utils --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y adduser --no-install-recommends && rm -rf /var/lib/apt/lists/*

ENV MYSQL_MAJOR 5.6
ENV MYSQL_VERSION

WORKDIR /tmp
RUN wget http://downloads.mysql.com/archives/get/file/mysql-server_${MYSQL_VERSION}-1debian7_amd64.deb-bundle.tar

RUN tar xf mysql-server_${MYSQL_VERSION}-1debian7_amd64.deb-bundle.tar
RUN dpkg -i mysql-common_${MYSQL_VERSION}-1debian7_amd64.deb
RUN dpkg-preconfigure -f noninteractive mysql-community-server_${MYSQL_VERSION}-1debian7_amd64.deb
RUN dpkg -i mysql-community-server_${MYSQL_VERSION}-1debian7_amd64.deb
RUN dpkg -i mysql-community-client_${MYSQL_VERSION}-1debian7_amd64.deb
RUN dpkg -i libmysqlclient18_${MYSQL_VERSION}-1debian7_amd64.deb

RUN rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql && chown mysql:mysql /var/lib/mysql

# comment out a few problematic configuration values
RUN sed -Ei 's/^(bind-address|log)/#&/' /etc/mysql/my.cnf

VOLUME /var/lib/mysql

COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3306
CMD ["mysqld"]
